set TARGET_VS=vs2017
if exist "_Compiler\vs2019" set TARGET_VS=vs2019

rd /q /s "_NRD_SDK"
mkdir "_NRD_SDK"
cd "_NRD_SDK"
mkdir "Lib"
mkdir "Lib\Debug"
mkdir "Lib\Release"
mkdir "Integration"
mkdir "Include"
mkdir "Shaders"
copy "..\_Build\%TARGET_VS%\Bin\Debug\NRD.dll" "Lib\Debug"
copy "..\_Build\%TARGET_VS%\Lib\Debug\NRD.lib" "Lib\Debug"
copy "..\_Build\%TARGET_VS%\Bin\Debug\NRD.pdb" "Lib\Debug"
copy "..\_Build\%TARGET_VS%\Bin\Release\NRD.dll" "Lib\Release"
copy "..\_Build\%TARGET_VS%\Lib\Release\NRD.lib" "Lib\Release"
copy "..\_Build\%TARGET_VS%\Bin\Release\NRD.pdb" "Lib\Release"
copy "..\NRD\Include\*" "Include"
copy "..\NRD\Integration\*" "Integration"
copy "..\NRD\Shaders\*.hlsl" "Shaders"
copy "..\CompileShaders\*.hlsl" "Shaders"
copy "..\README.md" "."
copy "..\LICENSE.txt" "."

